name: B1
label: SAE補助のみ
description: |
  共有正則化を無効化し、疎オートエンコーダによる補助損失のみを適用する設定。
train:
  base_config: configs/train.yaml
  overrides:
    seed: 20250214
    loss:
      alpha: 0.0
      beta: 0.1
      sae_recon_weight: 1.0
      sae_l1_weight: 0.001
      sae_target_sparsity: 0.05
    trainer:
      checkpoint_dir: checkpoints/ablations/B1
      tensorboard_dir: logs/train/ablations/B1/tensorboard
      history_path: logs/train/ablations/B1/history.jsonl
    output:
      report_path: reports/ablations/B1.json
