# トレーニング設定
seed: 20250214

data:
  processed_dir: data/processed
  splits_dir: data/splits
  batch_size: 4
  num_workers: 4
  pin_memory: true
  persistent_workers: false
  drop_last: false
  shuffle_train: true
  ignore_index: -100

loss:
  task_loss_type: cross_entropy
  task_ignore_index: -100
  task_label_smoothing: 0.0
  task_exact_match_weight: 0.1
  sae_recon_weight: 1.0
  sae_l1_weight: 0.001
  sae_target_sparsity: 0.05
  sae_adaptation_rate: 5.0
  sae_activation_threshold: 0.001
  share_rank: 8
  share_activation_threshold: 0.001
  share_min_group_size: 4
  alpha: 1.0
  beta: 1.0

optimizer:
  lr: 0.0003
  weight_decay: 0.01
  betas: [0.9, 0.95]

scheduler:
  warmup_steps: 0
  warmup_ratio: 0.1
  min_lr_ratio: 0.1

trainer:
  epochs: 50
  gradient_accumulation_steps: 1
  max_grad_norm: 1.0
  use_amp: true
  amp_dtype: bf16
  log_interval: 25
  eval_interval: 1
  checkpoint_dir: checkpoints
  tensorboard_dir: logs/train/tensorboard
  history_path: logs/train/history.jsonl
  device: null
